# Generated by Django 4.2.1 on 2023-05-26 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)])),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('NB', 'Non Binaire'), ('Tg', 'Transgenre'), ('GF', 'Gender Fluid'), ('Q', 'Queer'), ('Tv', 'Travesti')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(35)])),
            ],
        ),
    ]
